### ISSUE TITLE
Add PHP 8.5 support

### ISSUE THREAD

**Issue by victormacko** [brefphp/bref#2031]
Thank you everyone for making Bref - it's simply amazing!

I noticed the new version of PHP was released a few weeks ago - PHP 8.5, and wanted to see if could be added to the layers/runtimes, and in the extra-extensions too (i'm using GD).

Thank you in advance & again for all your hard work.

**Comment by mnapoli** [comment]
Hi Victor! PHP 8.5 support is available in Bref v3 (#1953), under the hood 8.5 requires specific versions of system libraries and supporting this in Bref v2 was not worth the effort as v3 is coming soon, ideally this month.

**Comment by victormacko** [comment]
Hey there Matthieu!

Oh awesome, thanks so much for that, I had no idea it was already a work in progress!

Let me know if you need some help with v3, was starting to run into some issues with 29s timeout with Lambda/API Gateway and looking at adding in some extra logging data to find our more about the underlying cause of the timeouts (separate project to the PHP 8.5 support though!).

Cheers,

Victor

**Comment by mnapoli** [comment]
For HTTP timeouts I've implemented some event handling in the Sentry integration to log to Sentry for Laravel and Symfony apps, but this is not in Bref's base itself, you'd have to implement it manually.

**Comment by victormacko** [comment]
Ah fair enough, i'll take a look into it.
I was thinking more to add the requested url at least (or something identifying what the lambda request actually was which caused the timeout) so it can be investigated and sorted out, rather than a very generic 'Timed out after 29s'.

**Comment by jonblatho** [comment]
@mnapoli, what is the recommended path to get a layer ARN for PHP 8.5 on arm64? We currently use the separate [layers.js](https://github.com/brefphp/layers.js/tree/v3) project to pull `arm-php-NN` layer versions (we were formerly on `arm-php-NN-fpm` for v2), and that repo doesn't seem to have lists of PHP 8.5 layers yet, even in the `v3` branch.

There's a list of PHP 8.5 images in this repo's `v3` branch, but I can't seem to get our function to run. If there's no fix for this just yet, could you please provide the latest layer ARN for Bref v3 / PHP 8.5 / arm64? Thanks!

**Comment by mnapoli** [comment]
@jonblatho during the beta phase the `layers.js` project won't be up to date. You can find the ARNs here: https://runtimes.bref.sh/

Once v3 is released as stable then `layers.js` will be up to date.

**Comment by victormacko** [comment]
Thank you for all your work on Bref v3, already updating a few projects to it which look like they're all working well :)
Still having some trouble with GD and the extensions but I raised a separate issue in that repo, hopefully it's just user error!
